### ISSUE TITLE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.13 (node_modules/webworker-threads):

### ISSUE THREAD

**Issue by isaklafleur** [morungos/wordnet#25]
Hi Stuart,

Thank you for contributing. I'm really eager to get up an running with this lib.

When I installed it I got below warnings and errors.

The package was installed so.. Nothing to worry about?  :)

```
> webworker-threads@0.7.13 install /Users/isaklafleur/Dropbox/Isak/Coding/Other/autoMDM/node_modules/webworker-threads
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to installthe standalone command line developer tools.
See `man xcode-select` for more details.

xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to installthe standalone command line developer tools.
See `man xcode-select` for more details.

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to installthe standalone command line developer tools.
See `man xcode-select` for more details.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/isaklafleur/Dropbox/Isak/Coding/Other/autoMDM/node_modules/webworker-threads
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.13 (node_modules/webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.13 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by morungos** [comment]
Hmmm. Well it isn't a direct dependency, and it's not immediately obvious how this is getting pulled in, and the log above doesn't show. 

The module certainly doesn't need webworkers, so this shouldn't be an issue to worry about, but I'll still to find some kind of a remedy, because this kind of error message soup always freaks me out, and I certainly don't want others to endure it.

**Comment by morungos** [comment]
I'm pretty sure now that this is: https://github.com/nodejs/node-gyp/issues/569, i.e., it's upstream, and as I said, I'm not wanting webworkers so it's somewhere in node-gyp/webworkers territory.
